name: appack
title: AppPack
version: 0.1.1
summary: Run apps made for any operating system
description: |
  AppPack is a cross-platform app launcher that runs apps made for any operating system.
  It supports virtually any operating system, including Windows, macOS, and Linux.
  It is designed to be as simple to use as possible.
  It makes use of virtualization technologies and RDP under the hood to run apps in a virtual machine.
confinement: strict
base: core24
license: GPL-3.0-only
source-code:
  - https://github.com/PaulCombal/appack-cli
website:
  - https://github.com/PaulCombal/appack-cli

apps:
  appack:
    command: bin/appack
    extensions: [gnome]
#    environment:
#      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
    plugs:
      - desktop # Needed to send notifications
      - network
      - network-bind
      - alsa
      - pulseaudio
      - x11
      - wayland
      - audio-playback
      - audio-record
      - kvm # Needed, try to request autoconnect
      - home
      - opengl
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - dot-local-share-applications

parts:
  snapbuildtools:
    source: https://github.com/sergio-costas/snap-build-tools.git
    source-depth: 1
    plugin: nil
    build-snaps: [ core24 ]
    override-pull: |
      craftctl default
      $CRAFT_PART_SRC/install

  virgl:
    after: [ snapbuildtools ]
    source: https://gitlab.freedesktop.org/virgl/virglrenderer.git
    source-tag: virglrenderer-1.2.0
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - meson
      - python3-yaml
      - libgbm-dev
      - libdrm-dev
      - zstd

  qemu:
    after: [ virgl ]
    source: https://gitlab.com/qemu-project/qemu.git
    source-tag: v10.1.2
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --target-list=x86_64-softmmu # Add more architectures here if needed, cf qemu-virgil-snap
      - --audio-drv-list=pa,sdl
      - --enable-libusb
      - --enable-sdl
      - --enable-spice
      - --enable-kvm
      - --enable-opengl
      - --enable-virglrenderer
      - --enable-slirp
      - --disable-user
      - --disable-gtk # Added by me
      - --disable-rbd # Added by me
    build-environment:
      - ACLOCAL_PATH: /usr/share/aclocal
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/snapcraft/current/bin/scriptlet-bin:$PATH
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    override-build: |
      $CRAFT_PROJECT_DIR/snapbuildtools/remove_common.py core24
      craftctl default
    build-packages:
      - bison
      - flex
      - gettext
      - libaio-dev
      - libbluetooth-dev
      - libbrlapi-dev
      - libbz2-dev
      - libcap-dev
      - libcap-ng-dev
      - libcacard-dev
      - libcurl4-gnutls-dev
      - libepoxy-dev
      - libfdt-dev
      - libgtk-3-dev
      - libglib2.0-dev
      - libglusterfs-dev
      - libibverbs-dev
      - libiscsi-dev
      - libjemalloc-dev
      - libjpeg8-dev
      - liblzo2-dev
      - libncurses5-dev
      - libnfs-dev
      - libnuma-dev
      - libpango1.0-dev
      - libpixman-1-dev
      - libpulse-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libseccomp-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libslirp-dev
      - libsnappy-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libusb-1.0-0-dev
      - libusbredirhost-dev
      - libusbredirparser-dev
      - libvde-dev
      - libvdeplug-dev
      - libvte-2.91-dev
      - libxml2-dev
      - libx11-dev
      - libxen-dev
      - libzstd-dev
      - ninja-build
      - xfslibs-dev
      - zlib1g-dev
    stage-packages:
      - ipxe-qemu
      - ipxe-qemu-256k-compat-efi-roms
      - libaio1t64
      - libasn1-8-heimdal
      - libboost-iostreams1.74.0
      - libboost-thread1.74.0
      - libbrlapi0.8
      - libcacard0
      - libcurl3-gnutls
      - libfdt1
      - libgfapi0
      - libgfrpc0
      - libgfxdr0
      - libglusterfs0
      - libhcrypto5t64-heimdal
      - libgssapi3-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libibverbs1
      - libiscsi7
      - libjemalloc2
      - libkrb5-26-heimdal
      - libldap2
      - liblmdb0
      - libnfs14
      - libnghttp2-14
      - libnuma1
      - libopus0
      - librados2
      - librbd1
      - librdmacm1
      - libroken19t64-heimdal
      - librtmp1
      - libsamplerate0
      - libsasl2-2
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libslirp0
      - libsnappy1v5
      - libsndio7.0
      - libspice-server1
      - libssh-4
      - libtirpc3
      - liburcu8
      - libusb-1.0-0
      - libusbredirhost1
      - libusbredirparser1
      - libvdeplug2
      - libwind0-heimdal
      - libxencall1
      - libxendevicemodel1
      - libxenevtchn1
      - libxenforeignmemory1
      - libxengnttab1
      - libxenmisc4.17t64
      - libxenstore4
      - libxentoolcore1
      - libxentoollog1
      - libxss1
      - multipath-tools
      - ovmf
      - python3-ldb
      - python3-talloc
      - seabios
      - libepoxy0 # Added by me
    prime:
      # Fix execstack warnings
      - -usr/share/qemu/s390-ccw.img
      - -usr/share/qemu/s390-netboot.img
      - -usr/share/qemu/openbios-ppc
      # Remove cruft
      - -usr/share/qemu/qemu-nsis.bmp
      - -lib/systemd/system/multipath-tools-boot.service

  appack:
    plugin: rust
    build-environment:
      - RUSTUP_TOOLCHAIN: stable
    source: .
    stage-packages:
      - libcurl3t64-gnutls
      - libpsl5t64
      - libicu74
      - libldap2
      - libnghttp2-14
      - libnuma1
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libxml2
      - libyajl2
      - freerdp3-x11
      - freerdp3-wayland
      - libpulse0
      - libavcodec60
    stage:
      # This will probably cause a nasty bug one day
      - -usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0

  appack-assets:
    plugin: dump
    source: .
    stage:
      - assets

  cleanup:
    after: [ qemu ]
    plugin: nil
    override-prime: |
      set -eux
      for CRUFT in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$CRUFT
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
      rm -f $CRAFT_PRIME/usr/share/qemu/openbios-sparc32
      rm -f $CRAFT_PRIME/usr/share/qemu/openbios-sparc64

plugs:
  dot-local-share-applications:
    interface: personal-files
    write:
      - $HOME/.local/share/applications